Repository dominant-strategies/go-quai, pull requests merged in 2023-02, with the labels that each got.

#647 Bug Fix: Added copies on all common.Hash to the CopyHeader function
  core/types/block.go
Labels: bug, invalid, perfomance, blocked

#661 Add quai HTTP API to default dist
  network.env.dist
Labels: enhancement

#643 bugfix: remove communicating the gasPrice in rpcTransactions
  internal/quaiapi/api.go
Labels: bug, invalid

#676 Remove broken Make targets
  Makefile
Labels: bug

#683 Specify logs directory in README
  README.md
Labels: documentation

#679 Add verbosity to network.env
  Makefile
  network.env.dist
Labels: enhancement

#698 Add syncmode to network.env
  Makefile
  network.env.dist
Labels: enhancement

#699 Fixed version name in broadcast, be sure to update bootnodes
  node/config.go
Labels: bug

#700 Enforce dom's difficulty is always greater than sub's difficulty
  consensus/blake3pow/consensus.go
Labels: enhancement
