Repository dominant-strategies/go-quai, pull requests merged in 2023-04, with the labels that each got.

#740 Helper function to translate from order number to string
  common/types.go
Labels: enhancement

#742 Automatically tag @core-dev for review in this repo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#714 Modify header hash to instead hash SealHash+nonce
  consensus/blake3pow/consensus.go
  consensus/blake3pow/sealer.go
  consensus/consensus.go
  core/types/block.go
  core/worker.go
  params/config.go
Labels: bug, enhancement

#801 Store timestamp once when picking pendingHeader
  core/slice.go
Labels: enhancement

#820 Patch CVE-2021-39137
  core/vm/instructions.go
  core/vm/interpreter.go
Labels: bug
